### ISSUE TITLE
evil worker

### ISSUE THREAD

**Issue by dl12300** [giacomolmb/DiscoFL#2]
Hello, I read the paper you provided, the paper mentioned that the data of malicious workers is randomly generated, where is this function mentioned in the code you provided?

**Comment by giacomolmb** [comment]
Hello, in the `Model.py` file you can see what happens during training if a worker is evil. 

More specifically, from line 78:
```python
if not self.isEvil:
    output = self.model(data.to(self.DEVICE))
else:
    output = self.model(self.garbage.to(self.DEVICE))
    target = torch.randint(0, 8, (64,1)).reshape(64)
```

To start a simulation with evil workers, add the flag `--num_evil` followed by the number of evil workers (make sure it is less than the number of total workers). 

Hope I cleared your doubts!
