### ISSUE TITLE
worker

### ISSUE THREAD

**Issue by dl12300** [giacomolmb/DiscoFL#3]
Thanks for the reply, I set the number of malicious workers to 1 as you instructed and adjusted the relevant code. According to my understanding, if the number of benevolent workers is set to 3, then the total number of workers participating in training is 4, but I observe that the output of the code still has only three workers participating in the model training. What is the reason for this? Did I misunderstand?

**Comment by giacomolmb** [comment]
The reason is that the evil worker is counted in the total number of workers. 

For instance, with `--num_workers 3` and `--num_evil 1` you will have a total of 3 workers, one of which will be "evil".

Hope this clarifies your doubt!
